name: Tinker with mysql
on:
  pull_request

jobs:
  tinker:
    runs-on: ubuntu-latest
    steps:
      - name: start mysql
        run: sudo service mysql start
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false
      - name: Install Dependencies
        run: pnpm i

      - name: Generate prisma deps
        run: npx prisma generate

      - name: Copy .env.test-action to .env.test and .env
        run: cp .env.test-action .env.test
      - name: Run Migrations
        run: pnpm run db:test:reset
